### ISSUE TITLE
뭐가 더 나은 코드인가요?

### ISSUE THREAD

**Issue by doublemetal** [organic-benefit/javascript#5]
민혁님이 맡으셨던 문서 마지막에 있는 [예제코드](https://github.com/organic-benefit/javascript/blob/master/this-and-object-prototype/05.Prototypes_2.md#links-as-fallbacks)를 보면

<br>

```javascript
var foo = {
    print: function() {
        console.log("주민혁");
    }
};

var bar = Object.create(foo);

// 불라불라

bar.print();    // 주민혁
```

<br>

```javascript
var foo = {
    print: function() {
        console.log("주민혁");
    }
};

var bar = Object.create(foo);

bar.myPrint = function() {
    this.print();
};

bar.myPrint();      // 주민혁
```

저자는 아래 코드가 더 낫다고 하는데, 어떻게 생각하시나요??

**Comment by doublemetal** [comment]
저번에 이거 얘기 했었나요..? ㅋㅋㅋ 기억이 안나네요

**Comment by lopiter** [comment]
이거 뭔가 예제가 이상한거 아닌가요? ㅋㅋㅋ
첫번째 예제는 뭔가 의미가 없어 보이는데요..^^
내일 누군가 발표하실 delegate에서 설명 해주실듯 하네요.ㅋㅋ

**Comment by miller-mh** [comment]
저번에는 프로토타입 상속을 중점적으로 설명하느라 시간도 없어서 설명을 뺐습니다.
물론 기석님이 말한대로 큰 의미도 없기도 했구요.

저자가 말한 의도는 아마도 '위임을 통한 메소드 호출에서 위임을 준 객체(자식객체와 비슷한)에서 위임 메소드(부모객체가 가진)를 한번 더 감싸는 것이 가독성면에서 더 나을 수도 있다' 라고 말한 것 같습니다.
코드는 몇 줄 추가되지만, bar의 경우 호출한 myPrint()만 따라가면 this.print()가 나오게 되고, 이 코드로 위임을 통해 myPrint()를 구현했다는 것을 조금 더 명확히 알 수 있는 장점을 의미한 것 같습니다. 

제가 저 코드를 넣었던 이유는 자바스크립트 언어에서 가독성이 좋게 코드를 짜는 방법을 알아두면 좋지 않을까 싶어서였습니다.(특히 this와 프로토타입을 이용할 때)
아직 영어 실력이 미숙해 저자의 의도를 정확히 파악하지 못 한 걸 수도 있습니다.
불필요하다면 해당 내용은 삭제하겠습니다.

**Comment by songeunwoo** [comment]
저희끼리 스터디 하는데 구지 삭제할 필요까진 없을거 같아요
동철님도 다시한번 집고 넘어가진 의미로 이야기 하신거 같아요 ㅎ

참고로 스크립트 코드를 작성할때 저렇게 가독성을 위해서 많이들 작성 하시더라구요^^

**Comment by doublemetal** [comment]
@minhyeokJu 
가독성이 좋은 코드를 작성하기 위해 여러가지 방법을 익히는 것은 좋은 시도라고 생각합니다^^*
그리고 제가 보기엔 저자가 계속 함정을 파고 있는 것 같아서요(OLOO 만세)
제가 생각하기에 아래쪽 코드의 가독성면에서의 효과는
print가 다른 객체로부터 온 녀석(링크된)이라고 개발자에게 알려줘서 엉뚱한 곳을 보지 않아도 되는(?) 것인 것 같은데요. 이건 실제로 유지보수를 해봐야 장단점을 잘 알 수 있을 것 같네요.

**Comment by miller-mh** [comment]
@doublemetal 
네, 저도 저자가 약간 위임쪽에만 너무 치중한 면이 많다고 생각이 들었는데요.
제가 자바스크립트로 많이 안 짜봐서, 저보다 잘하는 저자의 의견을 너무 의심없이 받아들일려고 한 경향이 있던 것 같습니다.

의견 주신 모든 분들 감사합니다.

**Comment by doublemetal** [comment]
@lopiter @minhyeokJu @songeunwoo @serivires @jjc98 
YDK javascript 스터디에 참여해주셔서 감사합니다.
새로운 스터디 방식도 나쁘지 않았던 것 같고, 다른 기술을 공부하다가
가끔씩 이 스터디로 돌아와도 좋을 듯 싶습니다^^;
